# Análisis de Tweets para predecir Marcas de Empresas
Alan Badillo Salas (badillo.soft@hotmail.com)

## Introducción aTweepy

Tweepy es una librería de Python para poder extraer tweets de Twitter y utilzar el API de desarrolladores en general. Por ejemplo, podemos crear tweets, podemos extraer tweets y hacer diversas funcionalidades con nuestra cuenta de desarrollador.

En este tutorial vamos a intentar obtener los tweets principales para distintas marcas como Coca-Cola, Uber, Nike, Dominos, Kmmx, etc.

Antes de comenzar demos tener una cuenta de desarrollador en Twitter, la cual podemos crear con una cuenta personal en: https://developer.twitter.com/

Una vez creada la cuenta de desarrollador deberemos crear una `app` llenando un formulario y una vez aprobada podemos ver las credenciales de acceso dentro de la `app` en la página de desarrolladores en la parte de `detail` y en `Keys and Tokens`.

In [62]:
import tweepy as ty

api_key = "WtS9C7zOviSXpV0kxNmerGAS1"
api_secret_key = "GIQl5JnPPs7IHRG62FqEP95yCr05nh4nw48HrM2pts1N35Yj8I"

access_token = "64889616-0Bc5p8Rr7rURMMcwixP9J1AkYl6iKRV9vAICK289P"
access_token_secret = "ndLcxm9X5meKfRCxz3HSun4NjvVkNthDo32E2c8Ehsd6C"

auth = ty.OAuthHandler(api_key, api_secret_key)
auth.set_access_token(access_token, access_token_secret)

api = ty.API(auth)

In [33]:
public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)
    print("-" * 80)

RateLimitError: [{u'message': u'Rate limit exceeded', u'code': 88}]

In [34]:
user = api.get_user("CocaColaMx")

print(user)

User(follow_request_sent=False, has_extended_profile=False, profile_use_background_image=True, _json={u'follow_request_sent': False, u'has_extended_profile': False, u'profile_use_background_image': True, u'profile_text_color': u'F0DFE2', u'default_profile_image': False, u'id': 145019819, u'profile_background_image_url_https': u'https://abs.twimg.com/images/themes/theme1/bg.png', u'verified': True, u'translator_type': u'regular', u'profile_location': None, u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/1059635699148775425/B70ZUgpk_normal.jpg', u'profile_sidebar_fill_color': u'D10426', u'entities': {u'url': {u'urls': [{u'url': u'https://t.co/Il6vxiylEV', u'indices': [0, 23], u'expanded_url': u'http://www.coca-cola.com.mx', u'display_url': u'coca-cola.com.mx'}]}, u'description': {u'urls': [{u'url': u'https://t.co/Il6vxiylEV', u'indices': [42, 65], u'expanded_url': u'http://www.coca-cola.com.mx', u'display_url': u'coca-cola.com.mx'}]}}, u'followers_count': 726238, u'pro

In [36]:
tweets = api.user_timeline("CocaColaMx")

for tweet in tweets:
    print(tweet.in_reply_to_status_id)
    print(tweet.text)
    print("-" * 80)

1060945181699014656
@C_D_M_X Estoy dando seguimiento a tu caso y este es tu número de folio 04816876. Puedes llamar sin costo a HOLA Co… https://t.co/bprRGkraFR
--------------------------------------------------------------------------------
1060283298222616576
@Krenml ¡Hola Karen! ¿Me puedes enviar un DM con tus datos para contactarte? Aviso de privacidad https://t.co/nhnHYVuP71
--------------------------------------------------------------------------------
1060942686746800133
@C_D_M_X ¡Gracias por avisar! ¿Me puedes compartir el día, hora y lugar? Quiero ayudarte.
--------------------------------------------------------------------------------
1060932865544740864
@Robert_Herz23 ¡Hola Robert! Por favor conserva el producto y llama sin costo al 01 800 704 44 00, para ayudarte co… https://t.co/d9VLxQ8xVe
--------------------------------------------------------------------------------
1060743763637690368
@LuisHer60845303 ¡Hola Luis! Por favor conserva el producto y llama sin costo al 01

In [ ]:
['contributors', 'truncated', 'text', 'is_quote_status',
 'in_reply_to_status_id', 'id', 'favorite_count', '_api', 
 'author', '_json', 'coordinates', 'entities', 'in_reply_to_screen_name', 
 'id_str', 'retweet_count', 'in_reply_to_user_id', 'favorited', 
 'source_url', 'user', 'geo', 'in_reply_to_user_id_str', 'lang', 
 'created_at', 'in_reply_to_status_id_str', 'place', 'source', 'retweeted']

In [39]:
for tweet in ty.Cursor(api.user_timeline, screen_name="CocaColaMx", timeout=100).items(1000):
    if tweet.in_reply_to_status_id == None:
        print(tweet.text)
        print("-" * 80)

BREAKING NEWS ⚡⚡⚡ Un invitado llega para subirle la temperatura al Coca-Cola Flow Fest. https://t.co/s4yfxhGqSj
--------------------------------------------------------------------------------
Algunos le ponen piña a sus tacos, otros se ofenden de hacerlo, pero sin importar cómo los comas son más ricos con… https://t.co/FgXHJQhJdy
--------------------------------------------------------------------------------
El kebab sabe más rico con Coca-Cola, pero qué prefieres ¿trompo de comida árabe o uno de pastor? 😍 https://t.co/g6UENC9FmC
--------------------------------------------------------------------------------
🚨 🚨 🚨ATENCIÓN 🚨 🚨 🚨 ¡El crew lo pidió y aquí lo tenemos! El cartel completo para esa noche de dembow en el… https://t.co/QtrFWfSGGT
--------------------------------------------------------------------------------
¿Si la milanesa no es de Milán, de dónde es? #SienteElSabor https://t.co/Tc1Es5gHcf
--------------------------------------------------------------------------------
Due

La decisión ganadora siempre es Coca-Cola. 😉👌🏻 https://t.co/YeAg1KNChw
--------------------------------------------------------------------------------
Fue un mes de emociones, intensidad, sorpresas y grandes goles, sin importar quién se llevó el trofeo, nosotros tam… https://t.co/eEercyYo0o
--------------------------------------------------------------------------------
¡Francia bicampeón de la Copa Mundial de la FIFA™! 🐔🏆🥇⚽ Gracias Rusia ya estamos #ListosPara Qatar https://t.co/v6KIgyZ7Gg
--------------------------------------------------------------------------------
#ListosPara los últimos minutos de la Copa Mundial de la FIFA™️ Rusia 2018 y ve ya por tu Coca-Cola. https://t.co/rNIohgMZra
--------------------------------------------------------------------------------
#ListosPara la gran final de la Copa Mundial de la FIFA™️ Rusia 2018 🏆⚽ ¿Quién crees que gane? https://t.co/xcGpFyxnrh
--------------------------------------------------------------------------------
Bélgica se queda

Cierra la fase de grupos y estamos agradecidos con el país que inventó el futbol. ¡#ListosPara estos partidos! ¿Dón… https://t.co/U45GVpl65b
--------------------------------------------------------------------------------
#ListosPara conocer los rivales de estos dos equipos en octavos de final #SienteElSabor https://t.co/TxrkU2w40f
--------------------------------------------------------------------------------
Vamos contra un viejo conocido y esperamos un gran encuentro. #DEMUESTRAQUECREES #NadaNosDetiene https://t.co/VkWyj7twAQ
--------------------------------------------------------------------------------
#ListosPara ver contra quién se enfrentará @miseleccionmx en octavos: 📺👀📺
--------------------------------------------------------------------------------
Juntos en una nueva etapa, juntos con @miseleccionmx #NadaNosDetiene  #DEMUESTRAQUECREES https://t.co/7R6ycsxqZu
--------------------------------------------------------------------------------
#DEMUESTRAQUECREES hasta el último

In [41]:
for tweet in ty.Cursor(api.user_timeline, screen_name="nikemexico", timeout=100).items(1000):
    if tweet.in_reply_to_status_id == None:
        print(tweet.text)
        print("-" * 80)

Equipado para superar las condiciones climáticas de la temporada, Nike Air Zoom Pegasus 35 Shield. 

Disponible aho… https://t.co/puzvjfvasA
--------------------------------------------------------------------------------
Inspirado en el Día de Muertos.
Hecho para honrar a las leyendas. 

Presentamos el nuevo jersey edición especial de… https://t.co/8CIPQmBRaX
--------------------------------------------------------------------------------
Con rasgos inspirados en el diseño original de 1982

https://t.co/tyUNpWjWZU
--------------------------------------------------------------------------------
Velocidad X Precisión.

Cualquiera que sea tu estilo, mantén el juego en movimiento.
Adquiere ahora los nuevos Merc… https://t.co/NOh856NEed
--------------------------------------------------------------------------------
El nuevo integrante de la familia Zoom también es uno de los más rápidos.

Diseñado para romper récords de velocida… https://t.co/GAx8uiFTNq
-----------------------------------

Hace 20 años ya era adelantado a su época, ahora está de vuelta en su edición dorada para brillar en cada paso.… https://t.co/UhA3WHuga8
--------------------------------------------------------------------------------
Diseñados para volar. 

Los nuevos Nike Air Zoom Pegasus 35.

Disponibles ahora: https://t.co/aCDdI3LpmQ

#nikezoom https://t.co/e9RStsoVph
--------------------------------------------------------------------------------
Uno de los colorways favoritos del AJ3.

Presentamos los #AirJordan 3 'Katrina'.

Disponibles a las 2:00 A.M. aquí:… https://t.co/ytFypVfH9R
--------------------------------------------------------------------------------
El famoso “Curry” está de vuelta con su inigualable paleta de color.
Un ícono que no puede faltar en tu colección.… https://t.co/OCva0VGyDX
--------------------------------------------------------------------------------
Rindiendo homenaje a los mayores logros profesionales de Michael Jordan.

Los #AirJordan 1 Retro High OG.

Disponib… h

Aire fresco.

Los Nike Air VaporMax Flyknit 2 han llegado.

Consigue tu par aquí: https://t.co/hm3P0vc631… https://t.co/ApKGkY3q59
--------------------------------------------------------------------------------
Siempre estamos impulsando el aire al límite.
Aire grande, aire más grande, aire máximo.

Consigue tu par a las 2:0… https://t.co/gyO9vIq76i
--------------------------------------------------------------------------------
Esta semana, vuelve un clásico favorito de los coleccionistas y un ícono para estar en tendencia.

Consigue tu par,… https://t.co/xQzVZhqlU8
--------------------------------------------------------------------------------
Defiende tu legado con un Goya. 

Adquiere ahora el nuevo jersey de @PumasMX 2018: https://t.co/Wt3aMQ9JXK… https://t.co/o5DjocvKk0
--------------------------------------------------------------------------------
Estampados feroces para un look único.

Consigue tu par de  Air Max 1 Animal Pack a las 2:00 AM 3.17.18 aquí:… https://t.co/0qibiEn

RT @HirvingLozano70: #SOYMERCURIAL @nikemexico https://t.co/Ac36smG7mo
--------------------------------------------------------------------------------
Fue el primero en innovar con una cápsula visible de 270 grados y está de vuelta para fusionar tu estilo con las ca… https://t.co/P0b1DNdste
--------------------------------------------------------------------------------
Su estructura hace honor a su nombre y legado.
El Air Max 180 está de vuelta para fusionar el aire con las calles.… https://t.co/YxLLuGUCg4
--------------------------------------------------------------------------------
El Air Max 270 presume la cápsula de aire más grande creada hasta ahora por Nike, brinda un caminado suave que te a… https://t.co/xL1IHvclKu
--------------------------------------------------------------------------------
En tendencia desde 1972.
El Nike Blazer Low regresa con una composición de gamuza en el corte y una tratamiento pas… https://t.co/Lh6fswuaNj
------------------------------------------

El original inspirado en el tren bala de Japón está de vuelta, consigue tu par: https://t.co/305AY037MS https://t.co/BpOJSjLfpy
--------------------------------------------------------------------------------
Sabores de campeonato. 

#AirJordan 1 x Gatorade.
 
Disponibles este 27 de diciembre a las 2:00 A.M. aquí:… https://t.co/0rfD87WRUh
--------------------------------------------------------------------------------
El respeto se gana en la cancha, no se regala. Jugamos #SinFrío. 

https://t.co/hUhkMLjF1M
--------------------------------------------------------------------------------
Baila al rival con tu magia. Hazlo #SinFrío.

https://t.co/5cmD7XVxjL
--------------------------------------------------------------------------------
Aquí jugamos sin miedo, jugamos #SinFrío.

https://t.co/QbJl94b2ME
--------------------------------------------------------------------------------
El bra que lo cambia todo.

Presentamos el Nike FE/NOM Flyknit Bra. El primer bra deportivo con tecnología 

## Generar el Corpus de Aprendizaje

En nuestro análisis vamos a entrenar una RNN para que aprenda a reconocer un tweet como parte de una empresa. Es decir, dado un tweet (o texto en general) queremos predecir que marca se adapta mejor al tweet.

Por lo tanto, primero generaremos un corpus, el cuál especifique que tweet pertenece a que marca y así poder entrenar a la red. Una vez generado el corpus tendremos que predecir para un tweet arbitrario cuál es la marca que más se asocia al tweet.

Vamos entonces a partir generando una lista de marcas, dónde se indique la etiqueta de la marca, su `screen_name` de twitter y el número máximo de ejemplos que tomará de twitter.

In [60]:
marcas = [
    {
        "label": "nike",
        "feed": "nikemexico",
        "count": 10000
    },
    {
        "label": "coca-cola",
        "feed": "cocacolamx",
        "count": 10000
    },
    {
        "label": "dominos",
        "feed": "dominosmx",
        "count": 10000
    }
]

Vemos a definir una función que nos devuelva los tweets en el formato de lista de diccionarios.

Ejemplo: `[{ "label": "nike", "text": "..." }, { "label": "nike", "text": "..." }, ...]`

In [63]:
import tweepy

def get_tweets(api, label, feed, count):
    tweets = []
    for tweet in tweepy.Cursor(api.user_timeline, timeout=1000, screen_name=feed).items(count):
        if tweet.in_reply_to_status_id == None:
            tweets.append({
                "id": tweet.id,
                "label": label,
                "text": tweet.text,
                "date": tweet.created_at
            })
    print("Se encontraron {} tweets de {}".format(len(tweets), feed))
    return tweets

print(get_tweets(api, "dominos", "dominosmx", 100))

Se encontraron 6 tweets de dominosmx
[{'date': datetime.datetime(2018, 11, 9, 17, 0, 55), 'text': u'Una dieta a base de queso con pepperoni, ustedes saben de lo que hablo. \U0001f355', 'id': 1060940307846565889, 'label': 'dominos'}, {'date': datetime.datetime(2018, 11, 9, 0, 2, 2), 'text': u'@LauraEsquivel0 Hola Lau, lamentamos lo sucedido. Compartenos m\xe1s detalles v\xeda DM, accede al siguiente link;  https://t.co/HS8bbzIBHI', 'id': 1060683898458464256, 'label': 'dominos'}, {'date': datetime.datetime(2018, 11, 8, 23, 1, 3), 'text': u'La imponente Ram Axe puede ser tuya. Solo ordena el Combo Gamer aqu\xed:\nCompra el juego aqu\xed:\n#AssassinsCreedOdyssey\u2026 https://t.co/repxHKLuiW', 'id': 1060668549641986049, 'label': 'dominos'}, {'date': datetime.datetime(2018, 11, 8, 1, 41, 3), 'text': u'Tu voz, Alexa y Domino\u2019s, no s\xe9, pi\xe9nsalo. \xa1\xa1Bienvenido a M\xe9xico el servicio de voz de Amazon!! que llega con la  A\u2026 https://t.co/djN5VL5Ek9', 'id': 106034642870126592

Vamos ahora recolectar los tweets para todas las marcas.

In [64]:
tweets = []

for marca in marcas:
    tweets.extend(get_tweets(api, marca["label"], marca["feed"], marca["count"]))
    
print("Se encontraron {} tweets de todas las marcas".format(len(tweets)))

Se encontraron 523 tweets de nikemexico
Se encontraron 735 tweets de cocacolamx
Se encontraron 186 tweets de dominosmx
Se encontraron 1444 tweets de todas las marcas


Ahora que recolectamos todos los tweets para todas las marcas y ya están etiquetados, procederemos a guardarlos en un corpus (un `DataFrame` de pandas).

In [65]:
import pandas as pd

corpus = pd.DataFrame(tweets)

print(corpus.info())

print(corpus.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1444 entries, 0 to 1443
Data columns (total 4 columns):
date     1444 non-null datetime64[ns]
id       1444 non-null int64
label    1444 non-null object
text     1444 non-null object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 45.2+ KB
None
                 date                   id label  \
0 2018-11-08 17:04:47  1060578892422017024  nike   
1 2018-10-30 01:44:41  1057085850448580608  nike   
2 2018-10-19 19:54:36  1053373870927839232  nike   
3 2018-10-18 00:15:01  1052714632853389312  nike   
4 2018-10-12 18:14:37  1050811994339729408  nike   

                                                text  
0  Equipado para superar las condiciones climátic...  
1  Inspirado en el Día de Muertos.\nHecho para ho...  
2  Con rasgos inspirados en el diseño original de...  
3  Velocidad X Precisión.\n\nCualquiera que sea t...  
4  El nuevo integrante de la familia Zoom también...  


Finalmente guardamos el corpus con los tweets etiquetados para cada marca, para poder utilizarlo en análisis posteriores.

In [66]:
corpus.to_csv(open("tweet_corpus.csv", "w"), index=False, encoding="utf-8")

print("Corpus almacenado")

Corpus almacenado


## Clasificador de Texto a Marca

Vamos a contruir un clasificador RNN para predecir una Marca de Empresa a partir de un texto (por ejemplo un tweet).

In [107]:
import pandas as pd

corpus = pd.read_csv("http://badillosoft.com/tweet_corpus.csv")

corpus = corpus.sample(frac=1)

print(corpus.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1444 entries, 561 to 679
Data columns (total 4 columns):
date     1444 non-null object
id       1444 non-null int64
label    1444 non-null object
text     1444 non-null object
dtypes: int64(1), object(3)
memory usage: 56.4+ KB
None


In [108]:
print(corpus.head())

                     date                   id      label  \
561   2018-08-07 18:30:00  1026898266833739776  coca-cola   
589   2018-07-06 19:15:24  1015313282234806275  coca-cola   
115   2018-02-13 19:02:30   963488570467061760       nike   
1073  2017-12-07 19:01:00   938845818072780800  coca-cola   
825   2018-04-18 22:40:27   986736241172516865  coca-cola   

                                                   text  
561   Se pusieron guapos con los descuentos @italian...  
589   Nadie se resiste a unos deliciosos waffles bel...  
115   La innovación del aire está de vuelta.\nEl Vap...  
1073  El ganador ya fue notificado por DM. ¡Gracias ...  
825   #DEMUESTRAQUECREES y podrás ganar grandes prem...  


In [109]:
import text_util
from text_util import generate_sequences, generate_labels

x_train, x_test = generate_sequences(corpus["text"], thresh=1)

print(x_train[:3])

La máxima secuencia de palabras es: 26
Se encontraron 22659 palabras
Se encontraron 4881 palabras diferentes
Se analizarán 1155/1444 secuencias
Se validarán 289/1444 secuencias
[[   0    0    0    0    0    0    0    0    0    0    0 1522  994 4300
  4571 2325 4032 1778   40 2115 1962 1851 2749 1967 1601 1825]
 [   0    0    0    0    0    0    0    0    0 1853 1522 4750 2749  834
  2402 4218  732 1388 2499 4607 1838 2745 3394  654 2468 3442]
 [   0    0    0    0    0    0    0    0 3986 1409 2675  480 4667  654
  3866 1600 1121 3499 4077 2814 4667 3765 1601 2368 4337  156]]


In [110]:
y_train, y_test, categories = generate_labels(corpus["label"])

print(y_train[:10])

Se analizarán 1155/1444 etiquetas
Se validarán 289/1444 etiquetas
[[1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]]


In [111]:
print(categories)

{'dominos': 2, 'coca-cola': 0, 'nike': 1}


In [112]:
from keras.models import Sequential
from keras.layers import Embedding, GRU, LSTM, Dense

model = Sequential()

model.add(Embedding(
    input_dim=len(text_util.dictionary) + 1,
    output_dim=8,
    input_length=text_util.length
))

model.add(LSTM(16, return_sequences=True))
model.add(LSTM(8, return_sequences=True))
model.add(LSTM(4))

model.add(Dense(len(categories), activation="sigmoid"))

model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 26, 8)             39056     
_________________________________________________________________
lstm_4 (LSTM)                (None, 26, 16)            1600      
_________________________________________________________________
lstm_5 (LSTM)                (None, 26, 8)             800       
_________________________________________________________________
lstm_6 (LSTM)                (None, 4)                 208       
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 15        
Total params: 41,679
Trainable params: 41,679
Non-trainable params: 0
_________________________________________________________________
None


In [113]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
1155/1155 [==============================] - 9s 8ms/step - loss: 1.0701 - acc: 0.4883
Epoch 2/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.9870 - acc: 0.4978
Epoch 3/10
1155/1155 [==============================] - 4s 3ms/step - loss: 0.9203 - acc: 0.5186
Epoch 4/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.8276 - acc: 0.5887
Epoch 5/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.7783 - acc: 0.6043
Epoch 6/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.7298 - acc: 0.6095
Epoch 7/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.6778 - acc: 0.6061
Epoch 8/10
1155/1155 [==============================] - 4s 3ms/step - loss: 0.6207 - acc: 0.6632A: 2s - 
Epoch 9/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.5716 - acc: 0.9489
Epoch 10/10
1155/1155 [==============================] - 3s 3ms/step - loss: 0.5040 - acc: 0.9714


In [114]:
metrics = model.evaluate(x_test, y_test)

print(metrics)

289/289 [==============================] - 2s 7ms/step
[0.5892903503662162, 0.8166089965397924]


In [125]:
import numpy as np

text = "El destino de Grecia está en tus manos. Obtén el contenido exclusivo que puedes conseguir al ordenar el Combo Gamer."

text_vec = text_util.text_to_vec(text)
text_seq = text_util.text_to_sequence(text_vec)

test = np.array([text_seq])

predict = model.predict(test)[0]

print(predict)

[0.9147574  0.23467037 0.15598641]
